### ISSUE TITLE
NoClassDefFoundError after 

### ISSUE THREAD

**Issue by younes-io** [camunda-community-hub/dmn-scala#20]
Hello,

I get this error after installing the `dmn-scala\zeebe-worker` :

`❯ java -jar .\target\dmn-engine-zeebe-worker-1.6.1-SNAPSHOT-full.jar

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/logging/log4j/util/StackLocator$FqcnCallerLocator
        at org.apache.logging.log4j.util.StackLocator.<clinit>(StackLocator.java:37)
        at org.apache.logging.log4j.util.StackLocatorUtil.<clinit>(StackLocatorUtil.java:33)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:44)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:48)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:30)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358)
        at org.camunda.dmn.package$.<clinit>(package.scala:7)
        at org.camunda.dmn.zeebe.ZeebeDmnWorkerApplication.start(ZeebeDmnWorkerApplication.scala:52)
        at org.camunda.dmn.zeebe.ZeebeDmnWorkerApplication$.main(ZeebeDmnWorkerApplication.scala:27)
        at org.camunda.dmn.zeebe.ZeebeDmnWorkerApplication.main(ZeebeDmnWorkerApplication.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.util.StackLocator$FqcnCallerLocator
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 10 more
Exception in thread "shutdownHook1" java.lang.NoClassDefFoundError: Could not initialize class org.camunda.dmn.package$
        at org.camunda.dmn.zeebe.ZeebeDmnWorkerApplication.stop(ZeebeDmnWorkerApplication.scala:73)
        at org.camunda.dmn.zeebe.ZeebeDmnWorkerApplication$.$anonfun$main$3(ZeebeDmnWorkerApplication.scala:25)
        at scala.sys.ShutdownHookThread$.$anonfun$apply$1(ShutdownHookThread.scala:35)
        at java.base/java.lang.Thread.run(Thread.java:832)`

I also get the same error when I run `java -jar .\dmn-engine-zeebe-worker-1.6.0-full.jar`.

Is this repo being maintained or is it obsolete ?

Environment : 

* Windows 10
* Java version : 
`❯ java -version 
java version "15.0.2" 2021-01-19 
Java(TM) SE Runtime Environment (build 15.0.2+7-27) 
Java HotSpot(TM) 64-Bit Server VM (build 15.0.2+7-27, mixed mode, sharing) `

**Comment by saig0** [comment]
@younes-io thank you for reporting :+1: 

I'll look into it :detective:

**Comment by saig0** [comment]
Ok. I can reproduce the issue in version `1.6.0`.

**Comment by saig0** [comment]
I fixed the issue with dependencies #22. I'll build a new release soon :rocket:

**Comment by saig0** [comment]
A new release is available: https://github.com/camunda-community-hub/dmn-scala/releases/tag/1.6.1
